# Generated by Django 5.2.15 on 2026-09-23 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('requested_context', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('access_status', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ContextProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(choices=[('professional', 'Professional'), ('gaming_social', 'Gaming & Social'), ('sports', 'Sports')], max_length=30)),
                ('display_name', models.CharField(max_length=100)),
                ('pronouns', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'context_type')},
            },
        ),
        migrations.CreateModel(
            name='StaticContextAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_key', models.CharField(max_length=100)),
                ('attribute_value', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('context_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_attributes', to='identity_core.contextprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=255, unique=True)),
                ('allowed_context', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDefinedContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_name', models.CharField(max_length=50)),
                ('display_title', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contexts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'context_name')},
            },
        ),
        migrations.CreateModel(
            name='DynamicContextAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_key', models.CharField(max_length=100)),
                ('attribute_value', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('dynamic_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='identity_core.userdefinedcontext')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('allowed_context', models.CharField(max_length=30)),
                ('is_allowed', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'client_name', 'allowed_context')},
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(max_length=30)),
                ('is_context_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'context_type')},
            },
        ),
    ]
